### PyNAMod
1) Получение огрубленных моделей структур ДНК, генерация линейных ДНК, объединение моделей.
2) Исследование конформаций с помощью моделирования методом Монте Карло.

![alt text](params.png "Title")

### Установка
https://github.com/intbio/PyNAMod \
Создание окружения:\
conda env create --file environment.yml

In [3]:
import pynamod

In [4]:
import warnings
warnings.filterwarnings('ignore')

### Анализ полноатомоных моделей

In [59]:
# Инициализация с помощью объекта mda Universe, pdb файла или pdb id
nucl = pynamod.DNA_Structure_from_Atomic(pdb_id='3LZ0',leading_strands=['I'])

Sending GET request to https://files.rcsb.org/download/3LZ0.pdb to fetch 3LZ0's pdb file as a string.


Получение геометрических параметров

In [60]:
nucl.analyze_DNA()

In [7]:
nucl.pairs_params

array([[ 9.70966553e-02,  1.21458773e-01,  1.04506395e+00,
         1.40082869e+01, -8.18639620e+00, -1.87471501e+01],
       [ 6.16556830e-01, -4.23762539e-01,  3.66543477e-01,
        -3.20760411e+00, -2.17225711e+01, -8.92783404e+00],
       [ 8.33555107e-01,  2.65378482e-01,  1.06420986e+00,
        -2.81835208e+01, -1.78276976e+01,  1.05650531e+01],
       [ 6.28470367e-01, -2.24858764e-01, -3.41788548e-01,
        -1.42074455e+01, -1.89152830e+01, -9.26753607e+00],
       [-7.82725737e-01, -3.61822368e-01,  3.76318565e-01,
        -1.82251556e-01, -1.32761271e+01,  9.31395960e+00],
       [-1.02498035e+00, -4.53235488e-01,  2.54811697e-01,
        -8.89859618e+00, -2.04995738e+01, -1.07535740e+00],
       [-6.11318359e-01, -3.52076437e-01,  3.07540793e-01,
        -2.76799155e-01, -5.47535216e+00, -8.99594577e+00],
       [-1.38214834e-01, -9.47341879e-02,  3.10726313e-01,
         1.44885175e+00, -1.19754173e+01,  5.70485838e+00],
       [-3.41111946e-01,  7.24897008e-01,  6.920

In [8]:
nucl.steps_params[:3]

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-0.10334615, -1.03161687,  4.00980046,  5.4320164 , -2.15971877,
        37.18377021],
       [ 1.00706973, -0.13734141,  3.68751642, -0.26050816, -0.06127103,
        41.36494789]])

In [9]:
nucl.base_ref_frames[4]

array([[-2.46070998e-01, -9.18613029e-01, -3.09191148e-01,
         0.00000000e+00],
       [-9.68724189e-01,  2.22563848e-01,  1.09721376e-01,
         0.00000000e+00],
       [-3.19767137e-02,  3.26520192e-01, -9.44649170e-01,
         0.00000000e+00],
       [-5.73954147e+01, -4.38646216e+01,  6.63660857e+01,
         0.00000000e+00]])

In [7]:
nucl.get_dataframe().head()

resid1 segid1 restype1 restype2 segid2  resid2     Shear   Stretch  \
0     -72      I        A        T      J      72  0.097097  0.121459   
1     -71      I        T        A      J      71  0.616557 -0.423763   
2     -70      I        C        G      J      70  0.833555  0.265378   
3     -69      I        A        T      J      69  0.628470 -0.224859   
4     -68      I        G        C      J      68 -0.782726 -0.361822   

    Stagger     Buckle    Prop-Tw    Opening     Shift     Slide      Rise  \
0  1.045064  14.008287  -8.186396 -18.747150  0.000000  0.000000  0.000000   
1  0.366543  -3.207604 -21.722571  -8.927834 -0.103346 -1.031617  4.009800   
2  1.064210 -28.183521 -17.827698  10.565053  1.007070 -0.137341  3.687516   
3 -0.341789 -14.207446 -18.915283  -9.267536 -0.740422  0.309669  2.985010   
4  0.376319  -0.182252 -13.276127   9.313960  1.459504 -0.116359  3.047685   

       Tilt       Roll      Twist  
0  0.000000   0.000000   0.000000  
1  5.432016  -2.159719  37.183770  
2 -0.260508  -0.061271  41.364948  
3  7.616249  11.300466  28.885169  
4 -5.397753  -4.828530  32.891446

Получение огрубленной модели белка

In [61]:
nucl.analyze_protein()

Визуализация

In [11]:
# Перемещение первой пары в начало координат
nucl.move_to_coord_center()

nucl.view_structure()

NGLWidget()

### Генерация линейной ДНК

In [62]:
seq = 'atcg'*25
dna_gen = pynamod.DNA_Structure_Generated(seq)

In [29]:
#fix
dna_gen.steps_params[5,3:] += 90

In [31]:
dna_gen.base_ref_frames = rebuild_by_full_par_frame_numba(dna_gen.steps_params)

In [32]:
dna_gen.view_structure()


NGLWidget()

### Объединение структур

Инициализация стурктуры с белком cas9

In [44]:
cas = pynamod.DNA_Structure_from_Atomic(pdb_id='5Y36',leading_strands=['C'])

Sending GET request to https://files.rcsb.org/download/5Y36.pdb to fetch 5Y36's pdb file as a string.


In [45]:
cas.analyze_DNA()

In [48]:
cas.proteins = [cas.proteins[1]]

In [49]:
cas.analyze_protein(n_cg_beads=30)

In [38]:
cas.get_dataframe()

resid1 segid1 restype1 restype2 segid2  resid2     Shear   Stretch  \
0        1      C        A        T      D      55  0.029066 -0.006668   
1        2      C        C        G      D      54  0.242727 -0.124775   
2        3      C        A        T      D      53  0.060091 -0.090110   
3        4      C        T        A      D      52 -0.090729 -0.091878   
4        5      C        T        A      D      51 -0.061903 -0.125165   
5        6      C        T        A      D      50  0.189716 -0.212127   
6        7      C        T        A      D      49 -0.090354 -0.084898   
7        8      C        C        G      D      48  0.312910 -0.173799   
8        9      C        G        C      D      47 -0.338506 -0.158373   
9       10      C        G        C      D      46 -0.434022 -0.192000   
10      11      C        G        C      D      45 -0.283883 -0.181668   
11      12      C        A        T      D      44 -0.023938 -0.117008   
12      13      C        T        A      D      43  0.059450 -0.147494   
13      14      C        G        C      D      42 -0.195969 -0.122106   
14      15      C        G        C      D      41 -0.420779 -0.143088   
15      16      C        T        A      D      40 -0.043910 -0.104982   
16      17      C        C        G      D      39  0.455266 -0.166508   
17      18      C        C        G      D      38  0.206713 -0.110998   
18      19      C        T        A      D      37 -0.210266  0.028949   
19      20      C        C        G      B      20  0.503099 -0.167237   
20      21      C        A        U      B      19  0.313361  0.119625   
21      22      C        T        A      B      18 -0.072622  0.158174   
22      23      C        G        C      B      17 -0.251562 -0.070349   
23      24      C        A        U      B      16  0.020955  0.019675   
24      25      C        A        U      B      15  0.164021 -0.155028   
25      26      C        C        G      B      14  0.376189 -0.170416   
26      27      C        G        C      B      13 -0.090438 -0.119441   
27      28      C        A        U      B      12  0.136834 -0.036430   
28      29      C        C        G      B      11  0.447807 -0.209644   
29      30      C        T        A      B      10 -0.034969  0.017338   
30      31      C        G        C      B       9 -0.306260 -0.151715   
31      32      C        G        C      B       8 -0.317675 -0.113899   
32      33      C        A        U      B       7 -0.105534 -0.055055   
33      34      C        G        C      B       6 -0.330231 -0.120356   
34      35      C        C        G      B       5  0.414100 -0.190533   
35      36      C        G        C      B       4 -0.305069 -0.092463   
36      37      C        G        C      B       3  0.063403 -0.081595   
37      38      C        T        A      B       2 -0.072803  0.019643   
38      40      C        A        T      D      16  0.091201 -0.354327   
39      22      B        U        A      B      49  0.092226 -0.067915   
40      23      B        U        A      B      48 -0.134455 -0.039598   
41      24      B        U        A      B      47  0.098271 -0.083449   
42      24      D        C        G      D      27  0.550172  0.202362   
43      25      B        U        A      B      46 -0.031210 -0.018325   
44      26      B        A        U      B      45 -0.259988 -0.065540   
45      30      B        C        G      B      39  0.482892 -0.156503   
46      31      B        U        A      B      38 -0.000755 -0.054161   
47      32      B        A        U      B      37 -0.016504 -0.037650   
48      53      B        G        C      B      61 -0.563856 -0.180750   
49      54      B        G        C      B      60 -0.905234 -0.247483   
50      70      B        C        G      B      79  0.621595 -0.153690   
51      71      B        U        A      B      78 -0.009465 -0.027421   
52      72      B        U        A      B      77 -0.115136 -0.010969   
53      

In [51]:
cas.view_structure()

NGLWidget()

Объединение с нуклеосомой и линейной ДНК

In [55]:
nucl_temp = pynamod.DNA_Structure_from_Atomic(pdb_id='3LZ0',leading_strands=['I'],proteins=[])
nucl_temp.analyze_DNA()
nucl_temp.analyze_protein()

Sending GET request to https://files.rcsb.org/download/3LZ0.pdb to fetch 3LZ0's pdb file as a string.


In [56]:
combined = pynamod.DNA_Structure().append_structures([nucl,dna_gen,nucl_temp])
# или nucl.append_structures([cas,dna_gen])

In [57]:
combined.view_structure()

NGLWidget()

### Моделирование методом Монте-Карло

Подготовка расчетов энергий

In [58]:
import torch
import numpy as np

In [63]:
en = pynamod.Energy()

# Инициализация матриц силовых констант
nucl.move_to_torch()
en.set_energy_matrices(nucl)

Полная энергия: энергия изгиба ДНК + энергия электростатических взаимодействий + энергия взаимодействия частиц (в виде потенциала Леннарда Джонса или сигмоиды)

In [64]:
en.get_full_energy(nucl)

tensor(10760.6611)

Генерация списка шагов, которые будут изменяться при моделирование

In [66]:
movable_steps = torch.ones(nucl.steps_params.shape[0],dtype=bool)

In [67]:
movable_steps

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True])

Запуск моделирования

In [68]:
it = pynamod.Iterator(nucl,en)

In [69]:
frames, energies = it.run(target_accepted_steps=500,movable_steps=movable_steps)

Steps:   0%|          | 0/1000000.0 [00:00<?, ?it/s]

Acceptance rate:   0%|          

target accepted steps reached
accepted_steps 500


In [ ]:
frames

### Применение ограничений на взаимное положение пар ДНК

Для получения определенных конформаций структуры в расчет можно вводить ожидаемые геометрические параметры между любыми двумя парами ДНК

In [20]:
from pynamod.external_forces.restraint import Restraint
from pynamod.energy.energy_constants import BDNA_step
from pynamod.geometry.bp_step_geometry import rebuild_by_full_par_frame_numba

Получение кольцевой ДНК из линейной

In [71]:
# Индексы пар, на которые накладывается ограничение
ind1,ind2 = 0, -1

# Коэффицент этого ограничения в формуле полной энергии
force_const = 500

# Целевые геометрические параметры
params = torch.Tensor(BDNA_step[6:])

# Допустимое отклонение
dev = torch.ones(1)*0.1

# Инициализация
restr = Restraint(ind1,ind2,force_const,params,dev)

Подготовка расчета энергии

In [72]:
en_linear = pynamod.Energy()
dna_gen.move_to_torch()
en_linear.set_energy_matrices(dna_gen)
en_linear.add_restraints([restr])

In [49]:
it = pynamod.Iterator(dna_gen,en_linear)
movable_steps = torch.ones(dna_gen.steps_params.shape[0],dtype=bool)

In [50]:
frames,energies = it.run(movable_steps=movable_steps,target_accepted_steps=100000)

Steps:   0%|          | 0/1000000.0 [00:00<?, ?it/s]

Acceptance rate:   0%|          

interrupted!
accepted_steps 27295


In [51]:
dna_gen.base_ref_frames = rebuild_by_full_par_frame_numba(np.array(frames[-1]))

In [52]:
dna_gen.view_structure()

NGLWidget()